---

###############################
# CFME Workload and Worker Appliances to Create
###############################

cfme_appliances:
  multiple: []
  # multiple:
  #   - vms:
  #     - vm_name: CF-Scale-R0000-Worker-5710-1-statsd
  #       template: h25-5.7.1.3-1
  #     - vm_name: CF-Scale-R0000-Worker-5710-2-statsd
  #       template: h25-5.7.1.3-1
  #     - vm_name: CF-Scale-R0000-Worker-5710-3-statsd
  #       template: h25-5.7.1.3-1
  #     - vm_name: CF-Scale-R0000-Worker-5710-4-statsd
  #       template: h25-5.7.1.3-1
  #     - vm_name: CF-Scale-R0000-Worker-5710-5-statsd
  #       template: h25-5.7.1.3-1
  #     clone_template: True
  #     cluster: c05-h25-Local
  #     disk_location: c05-h25-Local
  #     disks: []
  #     NICS:
  #       - vlan
  #       - ovirtmgmt
  #       - 10gnic
  #     cpus: 4
  #     cores: 4
  #     memory_size: 16 # in GB
  #     host: c05-h25
  #     vm_type: server
  #     migrate: pinned

  single:
  - vm_name: CF-R0000-DB-Workload-5.5.5.2
    template: cloudforms-4.0-template
    clone_template: False
    cluster: Default
    disk_location: vmstorage
    disks: []
    NICS: []
    cpus: 4
    cores: 4
    memory_size: 16 # in GB
    host: perf-test-01
    vm_type: server
    migrate: migratable

  - vm_name: CF-R0000-5552-Worker-01
    template: cloudforms-4.0-template
    clone_template: False
    cluster: Default
    disk_location: vmstorage
    disks:
      vmdb:
        size: 20 # in GB
        interface: virtio
        format: cow
        location: vmstorage
        allocation: thin
      vmdb2:
        size: 20 # in GB
        interface: virtio
        format: cow
        location: vmstorage
        allocation: clone
    NICS:
      - rhevm
      - ovirtmgmt
    cpus: 4
    cores: 4
    memory_size: 16 # in GB
    host: perf-test-01
    vm_type: desktop
    migrate: pinned
